
/*
--------------
	ROLES
--------------
*/

-- Cliente Básico
MERGE INTO ROLE 
  USING (VALUES 'ROLE_BASIC') L (NAME)
  ON (ROLE.NAME=L.NAME)
  WHEN NOT MATCHED THEN INSERT (NAME) VALUES (L.NAME);

-- Administrativo
MERGE INTO ROLE 
  USING (VALUES 'ROLE_ADMIN') L (NAME)
  ON (ROLE.NAME=L.NAME)
  WHEN NOT MATCHED THEN INSERT (NAME) VALUES (L.NAME);